export const koppen = {
  BSk: { color: "#ffff66", title: "Cold semi-arid" },
  Dfa: { color: "#66ffff", title: "Hot-summer humid continental" },
  Dfb: { color: "#00ffff", title: "Warm-summer humid continental" },
  Csb: { color: "#00ff66", title: "Warm-summer Mediterranean" },
  BWk: { color: "#ff6633", title: "Cold desert" },
  Cfa: { color: "#00ff00", title: "Humid subtropical" },
  Cfb: { color: "#66ff00", title: "Temperate oceanic" },
  Csa: { color: "#006600", title: "Hot-summer Mediterranean" },
  Dsb: {
    color: "#000066",
    title: "Mediterranean-influenced warm-summer humid continental",
  },
  Dfd: {
    color: "#0000ff",
    title: "Extremely cold subarctic",
  },
  Cwa: { color: "#006633", title: "Monsoon-influenced humid subtropical" },
  Cwb: { color: "#5fc765", title: "Monsoon-influenced temperate oceanic" },
  Cwc: { color: "#369633", title: "Monsoon-influenced subpolar oceanic" },
  Aw: {
    color: "#ff6666",
    title: "Tropical savanna with dry-winter",
  },
  BSh: { color: "#ffff00", title: "Hot semi-arid" },
  BWh: { color: "#ff6600", title: "Hot desert" },
  Af: { color: "#ff0000", title: "Tropical rainforest" },
  Dsa: {
    color: "#000099",
    title: "Mediterranean-influenced hot summer humid continental",
  },
  Am: { color: "#ff0000", title: "Tropical monsoon" },
  Dfc: { color: "#0066ff", title: "Subarctic" },
  Dsc: { color: "#983396", title: "Mediterranean-influenced subarctic" },
  Dwb: {
    color: "#003366",
    title: "Monsoon-influenced warm-summer humid continental",
  },
  Dwa: {
    color: "#6666ff",
    title: "Monsoon-influenced hot-summer humid continental",
  },
  Cfc: { color: "#66ff66", title: "Subpolar oceanic" },
  Dwc: { color: "#000033", title: "Monsoon-influenced subarctic" },
  Dsd: {
    color: "#8e5d92",
    title: "Mediterranean-influenced extremely cold subarctic",
  },
  Dwd: {
    color: "#30008a",
    title: "Monsoon-influenced extremely cold subarctic",
  },
  ET: { color: "#ff00ff", title: "Tundra" },
  EF: { color: "#660033", title: "Ice cap" },
} as const;
